---
title: "Final Project Evaluation"
author: "Group 12"
date: "2025-11-07"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

knitr::opts_knit$set(root.dir = rprojroot::find_root('.here'))
```

```{r}
source("00_requirements.R")
search()
```


**DATA FROM 1910s:**
```{r}
#Loading and cleaning 1910s books
files_1910s <- list.files("books_1910s", full.names = TRUE)
files_1910s

books_1910s <- lapply(files_1910s, function(f) {
  readLines(f, encoding = "UTF-8") %>%
    str_trim() %>% #removes leading/trailing whitespace
    str_replace_all("\n", " ") %>%  # remove newline characters
    str_flatten(collapse = " ") %>%  # combine with spaces
    str_squish() %>%  # remove extra whitespace
    str_to_lower() #make lowercase
  
})
names(books_1910s) <- basename(files_1910s)

# check second book
#nchar(books_1910s[[2]])  # Character count
#substr(books_1910s[[2]], 1, 200)  # First 200 characters


```

```{r}
#Checking first 200 characters of unclean data (1910s)
substr(books_1910s[[2]], 1, 200) 
```


```{r}
#Filtering out stop words (1910s)
stop_words <- c("a", "an", "the", "but", "or", "that", "so", "of", "to", "in", "for", "with", "for", "i")
pattern <- paste0("\\b(", paste(stop_words,collapse = "|"), ")\\b")
cleaned_text_1910s <- str_replace_all(books_1910s,regex(pattern, ignore_case = TRUE),"")
```


```{r}
#Checking first 200 characters of cleaned data (1910s)
substr(cleaned_text_1910s[[2]], 1, 200) 
```

**DATA FROM 2010s:**
```{r}
#Loading and cleaning 2010s books
files <- list.files("books_2010s", full.names = TRUE)
files

books_2010s <- lapply(files, function(f) {
  readLines(f, encoding = "UTF-8") %>%
    str_trim() %>% #removes leading/trailing whitespace
    str_replace_all("\n", " ") %>%  # remove newline characters
    str_flatten(collapse = " ") %>%  # combine with spaces
    str_squish() %>%  # remove extra whitespace
    str_to_lower() #make lowercase
  
})
names(books_2010s) <- files

# check second book
names(books_2010s)[2]
nchar(books_2010s[[2]])  # Character count
substr(books_2010s[[2]], 1, 200)  # First 200 characters

```

```{r}
#Checking first 200 characters of unclean data (2010s)
substr(books_2010s[[2]], 1, 200) 
```


```{r}
#Filtering out stop words (2010s)
stop_words <- c("a", "an", "the", "but", "or", "that", "so", "of", "to", "in", "for", "with", "for", "i")
pattern <- paste0("\\b(", paste(stop_words,collapse = "|"), ")\\b")
cleaned_text_2010s <- str_replace_all(books_2010s,regex(pattern, ignore_case = TRUE),"")
```


```{r}
#Checking first 200 characters of cleaned data (2010s)
substr(cleaned_text_2010s[[2]], 1, 200) 
```
